In [7]:
import array as arr
from array import *

val = array('d', [1 , 2, 3, 4, 5, 6,7,8,9.5])

print(val)

array('d', [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.5])


In [9]:
for i in range(0,len(val)):
    print(val[i],  end=' ')

1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.5 

In [8]:
for x in val:
    print(x, end=',')

1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.5,

In [10]:
print(val.typecode)

d


In [11]:
val.reverse()

In [12]:
for i in range(0, len(val)):
    print(val[i], end=",")

9.5,8.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0,

In [17]:
val.insert(1, 50)
val.append(100)
val[4] = 60

In [18]:
for i in range(0, len(val)):
    print(val[i], end=",")

9.5,50.0,50.0,50.0,60.0,7.0,6.0,5.0,4.0,3.0,2.0,1.0,100.0,100.0,

In [22]:
copyArray = array(val.typecode,(x  * 3 for x in val))
print(copyArray)

array('d', [28.5, 150.0, 150.0, 150.0, 180.0, 21.0, 18.0, 15.0, 12.0, 9.0, 6.0, 3.0, 300.0, 300.0])


In [23]:
copyArray.pop(3)

150.0

In [24]:
copyArray.pop()

300.0

In [25]:
copyArray.remove(15)

In [26]:
print(copyArray)

array('d', [28.5, 150.0, 150.0, 180.0, 21.0, 18.0, 12.0, 9.0, 6.0, 3.0, 300.0])


In [27]:
a = val[2:5]
print(a)

array('d', [50.0, 50.0, 60.0])


In [28]:
b = a[::-1]
print(b)

array('d', [60.0, 50.0, 50.0])


In [29]:
arr = array('i', [])

n = int(input('Enter a number: '))

for i in range(0, n):
    arr.append(int(input("Enter a next number: ")))

for x in arr:
    print(x, end= " ")

2 3 3 3 3 

In [6]:
import numpy as np

valnp = np.array([1,2,3,4,5.5, 'a'], )

In [4]:
for x in valnp:
    print(x, end=" ")

1 2 3 4 5.5 a 

In [9]:
check = np.linspace(10, 20, 5)

for x in check: 
    print(x, end=' ')

10.0 12.5 15.0 17.5 20.0 

In [10]:
valarrange  = np.arange(10,20, 2)
for x in valarrange: 
    print(x, end=' ')

10 12 14 16 18 

In [11]:
val = np.zeros(10)

In [12]:
print(val)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
zero = np.array(10)
print(zero)

10


In [14]:
one = np.array([1,2,3,4])
print(one)

[1 2 3 4]


In [15]:
two = np.array([[1,2,3],[5,6,3]])
print(two)

[[1 2 3]
 [5 6 3]]


In [16]:
three = np.array([[[1,2,3],[4,5,6]],[[4,3,2],[2,6,4]]])
print(three)

[[[1 2 3]
  [4 5 6]]

 [[4 3 2]
  [2 6 4]]]
